import { createSchema, Type, typedModel } from 'ts-mongoose';

export const contentSchema = createSchema({
    campusId: Type.number({ required: true }),
    languageId: Type.number({ required: true }),
    employeeInformation: Type.string({ required: true }),
    required: Type.string({ required: true }),
    requiredText: Type.string({ required: true }),
    badgeNumber: Type.string({ required: true }),    
    defaultDropdownAnswer: Type.string({ required: true }),
    department: Type.string({ required: true }),
    departments: Type.array({ required: true }).of({
        value: Type.string({ required: true }),
        text: Type.string({ required: true }),
    }),
    location: Type.string({ required: true }),
    locations: Type.array({ required: true }).of({
        value: Type.string({ required: true }),
        text: Type.string({ required: true }),
    }),
    symptoms: Type.string({ required: true }),
    symptomList: Type.array({ required: true }).of({
        value: Type.string({ required: true }),
        text: Type.string({ required: true }),
        sortOrder: Type.number({ required: true})
    }),
    yes: Type.string({ required: true }),
    no: Type.string({ required: true }),
    contact: Type.string({ required: true }),
    diagnosis: Type.string({ required: true }),
    attest: Type.string({ required: true }),
    understand: Type.string({ required: true }),
    firstName: Type.string({ required: true }),
    lastName: Type.string({ required: true }),
    id: Type.string({ required: true }),
    badgeId: Type.string({ required: true }),
    email: Type.string({ required: true }),
    sponsorFirstName: Type.string({ required: true }),
    sponsorLastName: Type.string({ required: true }),
    sponsorEmail: Type.string({ required: true }),
    destination: Type.string({ required: true }),
    purposeOfVisit: Type.string({ required: true }),
    contactEmail: Type.string({ required: true }),
    contactPhone: Type.string({ required: true }),
    contactAddress: Type.string({ required: true }),
    visitPersonName: Type.string({ required: true }),
    visitPersonEmail: Type.string({ required: true }),
    textPlaceholder: Type.string({ required: true }),
    validationSummary: Type.string({ required: true }),
    temperature: Type.string({ required: true }),
    temperatureInvalid: Type.string({ required: true }),
    building: Type.string({ required: true }),
    buildings: Type.array({ required: true }).of({
        value: Type.string({ required: true }),
        text: Type.string({ required: true }),
    }),
    badgeInformation: Type.string({ required: true }),
    badgeInstructions: Type.string({ required: true }),
    fullName: Type.string({ required: true }),
    vaccinationInformation: Type.string({ required: true }),
    vaccine1Given: Type.string({ required: true }),
    vaccine1Date: Type.string({ required: true }),
    vaccine2Given: Type.string({ required: true }),
    vaccine2Date: Type.string({ required: true }),    
    formCompleted: Type.string({ required: true }),    
    confirmationIsDisplayedText: Type.string({ required: true }),    
    confirmationIsNotDisplayedText: Type.string({ required: true }),
    saveAttestationText: Type.string({ required: true }),
    visitorInstructions: Type.string({ required: true }),
    temperatureFahrenheit: Type.string({ required: true }),
    temperatureCelsius: Type.string({ required: true }),
    temperatureNumber: Type.string({ required: true }),
    temperatureDecimal: Type.string({ required: true })
});
